### PR TITLE
Fix "Your running" to "You're running"

### PR DESCRIPTION
**Pull request by andschwa**

### CODE REVIEW

**Comment by smorks** [comment]
both versions sound kind of weird to me. i think it might sound better if we just got rid of the word "running". so that it's:

`Your version of KeePassHttp:`

**Comment by z3ntu** [comment]
Or just `Version of KeepassHttp:` ?

**Comment by smorks** [comment]
that works too!

**Comment by andschwa** [comment]
Looking at it closer, this was just a weird sentence all around. The original:

"Your running version of KeePassHTTP: ____" was correct, the possessive it was referring to with "your" was the version itself. It was just split because of the adverb (I think I just learned why my teachers always chided split infinitives).

I settled on:

> Your version of KeePassHttp:

To match the next sentence:

> Latest available version of KeePassHttp:

**Comment by z3ntu** [comment]
@andschwa I would leave out the `Your` completely as written in my last comment. That way it's more "objective" imo

**Comment by andschwa** [comment]
@z3ntu But then it's a bit ambiguous with respect to the line below it, it would read like this:

> Version of KeePassHttp:
> Latest available version of KeePassHttp:

Since there are two things, it makes more sense to qualify both instead of just the second.

**Comment by smorks** [comment]
@andschwa agreed. and thanks!

**Pull request merged**
